### ISSUE TITLE
Spec Discussion

### ISSUE THREAD

**Issue by jdcauley** [CardinalMedia/starling#1]
Update Agreed Spec:

- [ ] Global CLI option, but not required
- [ ] SCSS
- [ ] ES2017
- [ ] Partial Structure Templates
```
<?php get_template_part('partials/header'); ?>
  ...template code here...
<?php get_template_part('partials/footer'); ?>
```

Original:

Goals: 
* Accessible to beginner
* Modular
* Should function without global install requirements i.e. npm run dev vs gulp watch
* ES6 support
* SCSS

Up for discussion:

* Task Runner/Toolchain: Grunt, Gulp, Broccoli, Webpack et al?
* additional processes
* folder tree
* default template structure
* how DRY do we want to be

**Comment by ethanbutler** [comment]
Here are my thoughts, and I'm just spitballing here.

***

### Accessible to beginner
We should make it a priority to exemplify best practices – make sure that scripts/styles are enqueued in a really obvious way, make sure that any built-in functions/classes have proper doc blocks, etc. In other words, accessibility through thoroughness rather than simplicity.

### Modular
I think this is where we have an opportunity to make something special. Let's think about ways to enforce modularity as strictly as possible – i.e. having SCSS and JS files packaged with PHP partials. See folder structure notes below.

### No global installs
I like the idea of this, but I also think there's an opportunity to build some CLI tools that could be helpful in enforcing modularity.

### ES6 support
Let's go full on ES2017 support – I want await/async. Just an extra babel plugin.

### SCSS
I like that.

### Task Runner
I'm not picky here, though if modularity is a stated goal I think we could do some cool things with Webpack in particular.

### Folder Tree
Something like:

```
index.php
functions.php
style.css
assets/
  images/
  fonts/
  scss/
    _variables.scss
    _mixins.scss
partials/
  content/
     content.php
     _content.scss
    content.js
layouts/
  home/
    home.php
    _home.scss
   home.js
lib/
  vendor/
  ~~other lib code here~~
```

I'd really like to leverage Composer for this, so that we can make it easier to keep anything in `lib/vendor` up-to-date as best as possible.

We could also wrap things like shortcodes and widgets so that they use something in the `partials` dir.

### Default template structure
I'm honestly a fan of good ol'...

```
<?php get_template_part('partials/header'); ?>
  ...template code here...
<?php get_template_part('partials/footer'); ?>
```

...instead of using theme wrappers or anything. Yeah, it's not the DRYest thing in the world but it makes it significantly easier to do one-off header/footers in templates should for that to a need arise. I understand any opposition to this, though.

### DRYness
See notes on modularity.

**Comment by jdcauley** [comment]
### Accessible
I think providing quality documentation will be critical.
But I want to avoid cognitive overhead for some getting up and running in a real tool chain for the first time.

While I can get behind additional commands for potentially enabling things I want the minimum feature set to work inside of 2 Commands.

### Globals
So in npm we can create the power of a cli but call it without a global install.
So I'm not opposed to creating a CLI, but I want to make sure we implement so it can be run as a -g or as nom run our-cli add-cmb2
So if you installed the full Global you could init a theme potentially, but if you download the zip you can still add modules?
agreeable?

### Modularity
I'm not sure about component based packing I can def see the value, but it would very much fly in the face of the WP way. I'm not sure how well a pattern like that would scale. But I'm up for additional discussion

### File structure
Still up for discussion, re modularity, but generally yes. 
I've found theme wrappers have more harm than good in a huge number of cases, and a properly written index.php file will catch edge cases.
